import 'package:flutter/material.dart';

class LoginScreen extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Text("Login"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
                onPressed: () {
                  Navigator.pushReplacementNamed(context, "home");
                },
                child: Text("Open home")
            ),
            ElevatedButton(
                onPressed: () {
                  Navigator.pushNamed(context, "register");
                },
                child: Text("Open Register")
            )
          ],
        ),
      ),
    );
  }
}


///BuildContext is generated by flutter
///
/// push - push replacement - pop
